# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(550, 291)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        SettingsDialog.setFont(font)
        SettingsDialog.setModal(True)
        self.dialogLayout = QtWidgets.QGridLayout(SettingsDialog)
        self.dialogLayout.setObjectName("dialogLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply | QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.Langs_label = QtWidgets.QLabel(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Langs_label.setFont(font)
        self.Langs_label.setWordWrap(True)
        self.Langs_label.setObjectName("Langs_label")
        self.gridLayout.addWidget(self.Langs_label, 1, 0, 1, 1)
        self.langsWidget = QtWidgets.QListWidget(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.langsWidget.setFont(font)
        self.langsWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.langsWidget.setLineWidth(0)
        self.langsWidget.setObjectName("langsWidget")
        self.gridLayout.addWidget(self.langsWidget, 1, 1, 1, 1)
        self.MainLangsComboBox = QtWidgets.QComboBox(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MainLangsComboBox.setFont(font)
        self.MainLangsComboBox.setObjectName("MainLangsComboBox")
        self.gridLayout.addWidget(self.MainLangsComboBox, 0, 1, 1, 1)
        self.Service_label = QtWidgets.QLabel(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Service_label.setFont(font)
        self.Service_label.setWordWrap(True)
        self.Service_label.setObjectName("Service_label")
        self.gridLayout.addWidget(self.Service_label, 2, 0, 1, 1)
        self.MainLang_label = QtWidgets.QLabel(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.MainLang_label.setFont(font)
        self.MainLang_label.setWordWrap(True)
        self.MainLang_label.setObjectName("MainLang_label")
        self.gridLayout.addWidget(self.MainLang_label, 0, 0, 1, 1)
        self.ServicesComboBox = QtWidgets.QComboBox(SettingsDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ServicesComboBox.setFont(font)
        self.ServicesComboBox.setObjectName("ServicesComboBox")
        self.gridLayout.addWidget(self.ServicesComboBox, 2, 1, 1, 1)
        self.dialogLayout.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Настройки"))
        self.Langs_label.setText(_translate("SettingsDialog", "Языки по умолчанию:"))
        self.Service_label.setText(_translate("SettingsDialog", "Сервис автоперевода:"))
        self.MainLang_label.setText(_translate("SettingsDialog", "Основной язык:"))
