# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './GUI/TokenWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 88)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.KeyLabel = QtWidgets.QLabel(Form)
        self.KeyLabel.setObjectName("KeyLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.KeyLabel)
        self.KeyField = QtWidgets.QTextEdit(Form)
        self.KeyField.setObjectName("KeyField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.KeyField)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "API-ключ"))
        self.KeyLabel.setText(_translate("Form", "API-ключ:"))
